{% set name = "coincidence" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be29e3ed30222ab309784527b21e8669a2bc997ac456658fc7cf981d20566189

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - python
    - whey
    - pip
  run:
    - python
    - domdf-python-tools >=2.8.0
    - pytest >=6.2.0
    - pytest-regressions >=2.0.2
    - typing-extensions >=3.7.4.3

test:
  imports:
    - coincidence
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-coincidence/coincidence
  summary: Helper functions for pytest.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Helper functions for pytest.
  dev_url: https://github.com/python-coincidence/coincidence
  doc_url: https://coincidence.readthedocs.io

extra:
  recipe-maintainers:
    - snegireff
